version: '3.3'

services:
  app:
    container_name: app
    image: react-app
    command: npm start
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      - SERVER_PORT=${SERVER_PORT}
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
